version: '3.8'

services:
  money-tracker:
    build: .
    container_name: money-tracker
    restart: unless-stopped
    ports:
      - "8220:8220"
    volumes:
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
